### ISSUE TITLE
Need a possibility to clean up the notification Handler

### ISSUE THREAD

**Issue by dkleber89** [PLCHome/node-ads-api#3]
I´m wiriting at this time a plugin for ioBroker to communicate with Beckhoff PLC. 

I have implementet a automatic Sync of all Symbols in SymbolTable with the user can specify. My problem is when its happen that the notify Method with the same symname called. So every time the Symbol fires an additionaly Event when its changes.

That´s the reason i need to have a possibility to clean up the notification Handler. 

For Testing i have exposed the releaseNotificationHandles Method and it will work very well for me ... 

Is it possible to make these little changes also in your project?

**Comment by PLCHome** [comment]
done
